{{- if $.Values.ingress }}
{{ $releaseName := $.Values.name }}
{{ $servicePort := $.Values.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Values.name }}-{{ $.Values.environment }}
  name: {{ $.Values.ingress.name }}
  namespace: {{ printf "sid-%s" $.Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ $.Values.ingress.domain }}
    http:
      paths:
      {{- range $path := $.Values.ingress.paths}}
      - path: {{ $path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}
            port:
              number: {{ $servicePort }}
      {{- end }}
  tls:
  - hosts:
    - "shoppr.tv"
    secretName: certificate-secret
{{- end }}
